<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VinariCore\Module'                                   => __DIR__ . '/Module.php',
    'VinariCore\Controller\Console\EmailController'       => __DIR__ . '/src/VinariCore/Controller/Console/EmailController.php',
    'VinariCore\Entity\AbstractEmail'                     => __DIR__ . '/src/VinariCore/Entity/AbstractEmail.php',
    'VinariCore\Entity\AbstractEntity'                    => __DIR__ . '/src/VinariCore/Entity/AbstractEntity.php',
    'VinariCore\Entity\AbstractUser'                      => __DIR__ . '/src/VinariCore/Entity/AbstractUser.php',
    'VinariCore\Entity\AuditLog'                          => __DIR__ . '/src/VinariCore/Entity/AuditLog.php',
    'VinariCore\Entity\Error'                             => __DIR__ . '/src/VinariCore/Entity/Error.php',
    'VinariCore\Entity\Role'                              => __DIR__ . '/src/VinariCore/Entity/Role.php',
    'VinariCore\Entity\Session'                           => __DIR__ . '/src/VinariCore/Entity/Session.php',
    'VinariCore\Entity\SoftDeleteInterface'               => __DIR__ . '/src/VinariCore/Entity/SoftDeleteInterface.php',
    'VinariCore\Exception\ExceptionInterface'             => __DIR__ . '/src/VinariCore/Exception/ExceptionInterface.php',
    'VinariCore\Exception\InvalidArgumentException'       => __DIR__ . '/src/VinariCore/Exception/InvalidArgumentException.php',
    'VinariCore\Filter\Deleted'                           => __DIR__ . '/src/VinariCore/Filter/Deleted.php',
    'VinariCore\Fixture\AbstractFixture'                  => __DIR__ . '/src/VinariCore/Fixture/AbstractFixture.php',
    'VinariCore\Mvc\Controller\AbstractActionController'  => __DIR__ . '/src/VinariCore/Mvc/Controller/AbstractActionController.php',
    'VinariCore\Mvc\Controller\AbstractRestfulController' => __DIR__ . '/src/VinariCore/Mvc/Controller/AbstractRestfulController.php',
    'VinariCore\Session\SaveHandler\DbTableGateway'       => __DIR__ . '/src/VinariCore/Session/SaveHandler/DbTableGateway.php',
    'VinariCore\Session\SessionManager'                   => __DIR__ . '/src/VinariCore/Session/SessionManager.php',
    'VinariCore\Twig\VinariTwigExtension'                 => __DIR__ . '/src/VinariCore/Twig/VinariTwigExtension.php',
);
